/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package first.software;

//import static first.software.Reserve_Page.sa;
import static first.software.Login.booker;
import static first.software.Login.da;
import static first.software.Reserve_Page.Final_Recipt_Number;
import static first.software.Update.a;
import static first.software.Update.update_rec;
import static first.software.time.radio;
import static first.software.time.s_Date;
import java.io.InputStream;
import java.net.URLDecoder;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Computer World
 */
public class Bill extends javax.swing.JFrame {

    
  public static String Date;
  public static String Time;
  public static String b_date;
  public static String Hour;
  public static Connection cn;
  public static String biil="";  
    
    
    public Bill() {
        initComponents();
        bp.setText(booker);
       
     recc.setText(biil);
     //recc.setText(update_rec);
     
        
        
        //daTE  & tIME

        Calendar cal = new GregorianCalendar();
        int mon = cal.get(Calendar.MONTH)+1;
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        Date = String.valueOf(day)+"/"+String.valueOf(mon)+"/"+String.valueOf(year);
        daa.setText(String.valueOf(day)+"/"+String.valueOf(mon)+"/"+String.valueOf(year));
       
        
        int hour = cal.get(Calendar.HOUR_OF_DAY);
        int min = cal.get(Calendar.MINUTE);
        Hour = String.valueOf(hour);
        Time = String.valueOf(hour)+" : "+String.valueOf(min);
        ti.setText(String.valueOf(hour)+" : "+String.valueOf(min));
       
        
        //daTE  & tIME
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        bill = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        f = new javax.swing.JTextField();
        pbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        daa = new javax.swing.JLabel();
        ti = new javax.swing.JLabel();
        adr = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cell = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        bp = new javax.swing.JTextField();
        recc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        dis = new javax.swing.JTextField();
        target = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pbtn1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cell1 = new javax.swing.JTextField();
        recc1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        trans = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setResizable(false);

        table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price", "Ratio", "Total Quantity", "Total"
            }
        ));
        table.setShowHorizontalLines(false);
        table.setShowVerticalLines(false);
        table.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(table);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("       Billing Form");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Costumer Name");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("Bill Amnount");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("Amount Payble");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 153));
        jLabel7.setText("Amount Return");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 153));
        jLabel8.setText("Amount Remaining");

        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });

        pbtn.setText("Print Bill");
        pbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbtnActionPerformed(evt);
            }
        });

        jButton2.setText("Booking");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        daa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        daa.setText("Date");

        ti.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ti.setText("Time");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 153));
        jLabel9.setText("Address");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 153));
        jLabel10.setText("Cell Number");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 153));
        jLabel11.setText("Booking Person");

        bp.setEditable(false);

        recc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reccActionPerformed(evt);
            }
        });

        jButton1.setText("Recipt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 153));
        jLabel12.setText("Discount");

        dis.setText("0");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 153));
        jLabel13.setText("Target Date");

        pbtn1.setText("Update Bill");
        pbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbtn1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 153));
        jLabel14.setText("Cell Number 2");

        recc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recc1ActionPerformed(evt);
            }
        });

        jButton3.setText("Cell #");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 153));
        jLabel15.setText("Transport Expense");

        trans.setText("0");

        jMenu1.setText("File          ");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("New                  ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Print Reservation       ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Eixt         ");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Log Out              ");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Back");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Exit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(recc1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(recc, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(f, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                            .addComponent(adr)
                                            .addComponent(e)
                                            .addComponent(d)
                                            .addComponent(bill)
                                            .addComponent(name)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cell))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bp))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dis, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(target))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cell1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(trans)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(daa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(recc)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(recc1)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cell1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(trans)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(target, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(daa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ti)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        
        
        this.hide();
        new Reserve_Page().show();
        
        
        
      
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        this.hide();
        new Login().show();

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

        this.hide();
        new Welcome().show();

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        System.exit(0);

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void pbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbtnActionPerformed
   
        
//        DefaultTableModel model = (DefaultTableModel) table.getModel();
//        
//         while(model.getRowCount() > 0 )
//        {
//            for(int i=0; i<model.getRowCount();i++)
//            {
//                model.removeRow(i);
//            }
//
//        }
//         
//        
//         
//          String q = "create table bill_"+a.getText()+ "(Discription nvarchar(55), Vaalues nvarchar(55));" ;
//          System.out.println("bill_"+a.getText());
//           try {
//        
//        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
//        Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
//     
//        Statement st = con.createStatement();
//        st.execute(q);
//        JOptionPane.showMessageDialog(this, "Sucessfull");
//        }
//        catch(Exception ex){
//        JOptionPane.showMessageDialog(this, ex);
//        }
//           
//       
//         
//         
//         
//         String falto = " " ;
//         
//         
//          // database  
//           try {
//        
//        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
//        Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
//         
// String q2 = "insert into bill_"+a.getText()+ " values ('"+falto+"',' "+falto+" ')" ;
// String qq = "insert into bill_"+a.getText()+ " values ('Constumer Name','"+a.getText()+" Rs.. ')" ;
// String q1 = "insert into bill_"+a.getText()+ " values ('Bill Amount','"+bill.getText()+" Rs..')" ;
// String q3 = "insert into bill_"+a.getText()+ " values ('Amount Payble','"+d.getText()+" Rs..')" ;
// String q4 = "insert into bill_"+a.getText()+ " values ('Amount Return','"+e.getText()+" Rs..')" ;
// String q5 = "insert into bill_"+a.getText()+ " values ('Amount Remaining','"+f.getText()+" Rs..')" ;
// String tt = "insert into bill_"+a.getText()+ " values ('"+falto+"','=============')" ;
//
// Statement st = con.createStatement();
//    st.execute(q2);
//    st.execute(qq);
//    st.execute(q1);
//    st.execute(q3);
//    st.execute(tt);
//    st.execute(q4);
//    st.execute(q5);
//    
//     
//        }
//      catch(Exception ex){
//  JOptionPane.showMessageDialog(this, ex);
//      }
//  
//       //database  
//         
//      
//           
//            try{  
//       
//
//            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
//        
//        Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
//
//            PreparedStatement st = con.prepareStatement("select * from bill_"+a.getText()+"");
//                      
//            ResultSet rs = st.executeQuery();
//             table.setModel(DbUtils.resultSetToTableModel(rs));
//        }
//        catch(Exception ex)
//        {
//            System.out.println(ex);
//        }
//        
        
        
        //Booking Tyme
         try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
           
            
            String q = "insert into book_time values ('"+recc.getText()+"','"+radio+"','"+b_date+"')" ;
            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        //booking Tym
        
        
      // insert into book_time values ('"+recc.getText()+"','"+radio+"','"+b_date+"')
          
           //Pay

        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
           
            System.out.println(daa);
            String q = "insert into Pay values"
                    + " ('"+recc.getText()+"','"+name.getText()+"','"+bill.getText()+"','"+d.getText()+"','"+e.getText()+"',"
                    + "'"+f.getText()+"','"+bp.getText()+"','"+cell.getText()+"','"+adr.getText()+"'"
                    + ",'"+da+"','"+dis.getText()+"','"+target.getText()+"','1','"+cell1.getText()+"','"+trans.getText()+"')" ;
            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
 
        //Pay
          
           String input =  JOptionPane.showInputDialog
        ("Press 1 for Thermal Printer\nPress 2 for Normal Printer", "");
          
          if(input.equals("1")){
          
          //report 
        try{
            
     
            
Connection cn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
//String report="E:\\ibti\\Data\\Java Data\\Owaise Pakwan Center\\Resturant\\src\\first\\software\\newReport.jrxml";

JasperDesign jd = JRXmlLoader.load("C:\\Users\\sony\\Documents\\NetBeansProjects\\Catering Software\\Owaise Pakwan Center (aptech)\\Resturant\\src\\first\\software\\billtherma.jrxml");

String qu = "select rs.recipt, rs.dish as Dish, rs.item as Item,rs.item_quantity as Item_Quantity,rs.item_rate as Item_Rate ,\n" +
"(rs.item_quantity * rs.item_rate) as Total, bt.booking_date,bt.booking_time, p.cos_name,(p.bill_amount - p.Discount)as bill,p.Discount,p.amount_payble\n" +
",p.amount_remain,p.amount_return,p.cell#,p.Adress,p.Booking_person,p.bill_amount,p.edit\n" +
" from reserve rs \n" +
"inner join book_time bt\n" +
"On rs.recipt = bt.recipt\n" +
"inner join Pay p\n" +
"on rs.recipt = p.recipt\n" +
"where rs.recipt = '"+recc.getText()+"' "
+"order by rs.dish";
JRDesignQuery jq = new JRDesignQuery();
jq.setText(qu);
jd.setQuery(jq);

JasperReport jsp = JasperCompileManager.compileReport(jd);
JasperPrint prn = JasperFillManager.fillReport(jsp,null,cn);
JasperViewer.viewReport(prn);

            
//        path = getClass().getResource("/first.software/newReport.jasper").getPath();
//        path = URLDecoder.decode(path, "UTF-8");
//        Connection cn =  new Conexion().conectar();
//        Map paramotord = new HashMap();
//        JasperReport report = (JasperReport)JRLoader.loadObject(path);
//        JasperPrint print = JasperFillManager.fillReport(report, paramotord, cn);
//        JasperViewer view = new JasperViewer(print, false);
//        view.setTitle("Owaise Pakwan Center");
//        view.setVisible(true);
        
        }
        
        catch(Exception ex)
        {
                       JOptionPane.showMessageDialog(this, ex);
        }
        
          //report
          
          }
          
          
          
          
          
          else if(input.equals("2")){
          
              //report 
        try{
            
     
            
Connection cn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
//String report="E:\\ibti\\Data\\Java Data\\Owaise Pakwan Center\\Resturant\\src\\first\\software\\newReport.jrxml";

JasperDesign jd = JRXmlLoader.load("C:\\Users\\sony\\Documents\\NetBeansProjects\\Catering Software\\Owaise Pakwan Center (aptech)\\Resturant\\src\\first\\software\\newReport.jrxml");

String qu = "select rs.recipt, rs.dish as Dish, rs.item as Item,rs.item_quantity as Item_Quantity,rs.item_rate as Item_Rate ,\n" +
"(rs.item_quantity * rs.item_rate) as Total, bt.booking_date,bt.booking_time, p.cos_name,(p.bill_amount - p.Discount)as bill,p.Discount,p.amount_payble\n" +
",p.amount_remain,p.amount_return,p.cell#,p.Adress,p.Booking_person,p.bill_amount,p.edit\n" +
" from reserve rs \n" +
"inner join book_time bt\n" +
"On rs.recipt = bt.recipt\n" +
"inner join Pay p\n" +
"on rs.recipt = p.recipt\n" +
"where rs.recipt = '"+recc.getText()+"' "
+"order by rs.dish";
JRDesignQuery jq = new JRDesignQuery();
jq.setText(qu);
jd.setQuery(jq);

JasperReport jsp = JasperCompileManager.compileReport(jd);
JasperPrint prn = JasperFillManager.fillReport(jsp,null,cn);
JasperViewer.viewReport(prn);

            
//        path = getClass().getResource("/first.software/newReport.jasper").getPath();
//        path = URLDecoder.decode(path, "UTF-8");
//        Connection cn =  new Conexion().conectar();
//        Map paramotord = new HashMap();
//        JasperReport report = (JasperReport)JRLoader.loadObject(path);
//        JasperPrint print = JasperFillManager.fillReport(report, paramotord, cn);
//        JasperViewer view = new JasperViewer(print, false);
//        view.setTitle("Owaise Pakwan Center");
//        view.setVisible(true);
        
        }
        
        catch(Exception ex)
        {
                       JOptionPane.showMessageDialog(this, ex);
        }
        
          //report
              
              
          }
         
        
        
    }//GEN-LAST:event_pbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

     
        new time().show();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
    
         String aa;
         int cc,dd,ee,ff;
         
         aa = name.getText();
         cc = Integer.parseInt(bill.getText());
         dd = Integer.parseInt(d.getText());
         
         if(dd == cc || dd > cc){
         
         f.setText("0");
         int cal = dd - cc ;
         e.setText(String.valueOf(cal));
         }
         
         
         
         else {
         
        e.setText("0");
        int cal = cc - dd ;
        f.setText(String.valueOf(cal));
         
         
         }
         
         
         ee = Integer.parseInt(e.getText());
         ff = Integer.parseInt(f.getText());
        
    }//GEN-LAST:event_dActionPerformed

    private void reccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reccActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        
            //table
        try{  
       

        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
        
        Connection con = 
        DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

        PreparedStatement st = con.prepareStatement
        ("select dish as Dish,item as Item,item_quantity as Item_Quantity,item_rate as Item_Rate ,\n" +
"(item_quantity * item_rate) as Total \n" +
"from reserve where recipt = '"+recc.getText()+"'"
                + "order by dish ");
                      
             ResultSet rs = st.executeQuery();
             table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
        //table
        
        
        
         //total
        try {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
        
        Connection con = 
        DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
        String a="0" ;
        PreparedStatement st = con.prepareStatement
        ("select sum(item_quantity * item_rate) as Total \n" +
        "from reserve where recipt = '"+recc.getText()+"'");
                      
             ResultSet rs = st.executeQuery();
             while(rs.next()){
             a = rs.getString("Total");
             }
             bill.setText(a);
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
        //total
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbtn1ActionPerformed

        
        
        
          //Update booking
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

            //int a = Integer.parseInt(bill) - Integer.parseInt(pay);
String q = "update book_time set booking_date='"+b_date+"',booking_time='"+radio+"' \n" +
"where recipt='O_B76300'" ;

            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        //Update booking
        
        
        
        
        
        
        
        
        
        
                //Updated Bill
        
        
        
         String input =  JOptionPane.showInputDialog
        ("Press 1 for Thermal Printer\nPress 2 for A4 Printer", "");
        
        
        if(input.equals("1")){
         //Updated Bill
          try{
            
    
Connection cn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
//String report="E:\\ibti\\Data\\Java Data\\Owaise Pakwan Center\\Resturant\\src\\first\\software\\newReport.jrxml";

JasperDesign jd = JRXmlLoader.load("C:\\Users\\sony\\Documents\\NetBeansProjects\\Catering Software\\Owaise Pakwan Center (aptech)\\Resturant\\src\\first\\software\\billtherma.jrxml");

String qu = "select rs.recipt, rs.dish as Dish, rs.item as Item,rs.item_quantity as Item_Quantity,rs.item_rate as Item_Rate ,\n" +
"(rs.item_quantity * rs.item_rate) as Total, bt.booking_date,bt.booking_time, p.cos_name,(p.bill_amount - p.Discount)as bill,p.Discount,p.amount_payble\n" +
",p.amount_remain,p.amount_return,p.cell#,p.Adress,p.Booking_person,p.bill_amount,p.edit\n" +
" from reserve rs \n" +
"inner join book_time bt\n" +
"On rs.recipt = bt.recipt\n" +
"inner join Pay p\n" +
"on rs.recipt = p.recipt\n" +
"where rs.recipt = '"+recc.getText()+"' "
+"order by rs.dish";
JRDesignQuery jq = new JRDesignQuery();
jq.setText(qu);
jd.setQuery(jq);

JasperReport jsp = JasperCompileManager.compileReport(jd);
JasperPrint prn = JasperFillManager.fillReport(jsp,null,cn);
JasperViewer.viewReport(prn);

            
//        path = getClass().getResource("/first.software/newReport.jasper").getPath();
//        path = URLDecoder.decode(path, "UTF-8");
//        Connection cn =  new Conexion().conectar();
//        Map paramotord = new HashMap();
//        JasperReport report = (JasperReport)JRLoader.loadObject(path);
//        JasperPrint print = JasperFillManager.fillReport(report, paramotord, cn);
//        JasperViewer view = new JasperViewer(print, false);
//        view.setTitle("Owaise Pakwan Center");
//        view.setVisible(true);
        
        }
        
        catch(Exception ex)
        {
                       JOptionPane.showMessageDialog(this, ex);
        }
        
        //Updated Bill
        }
        
        
        
        
        
        
        
        
        else if(input.equals("2")){
         //Updated Bill
          try{
            
    
Connection cn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
//String report="E:\\ibti\\Data\\Java Data\\Owaise Pakwan Center\\Resturant\\src\\first\\software\\newReport.jrxml";

JasperDesign jd = JRXmlLoader.load("C:\\Users\\sony\\Documents\\NetBeansProjects\\Catering Software\\Owaise Pakwan Center (aptech)\\Resturant\\src\\first\\software\\newReport.jrxml");

String qu = "select rs.recipt, rs.dish as Dish, rs.item as Item,rs.item_quantity as Item_Quantity,rs.item_rate as Item_Rate ,\n" +
"(rs.item_quantity * rs.item_rate) as Total, bt.booking_date,bt.booking_time, p.cos_name,(p.bill_amount - p.Discount)as bill,p.Discount,p.amount_payble\n" +
",p.amount_remain,p.amount_return,p.cell#,p.Adress,p.Booking_person,p.bill_amount,p.edit\n" +
" from reserve rs \n" +
"inner join book_time bt\n" +
"On rs.recipt = bt.recipt\n" +
"inner join Pay p\n" +
"on rs.recipt = p.recipt\n" +
"where rs.recipt = '"+recc.getText()+"' "
+"order by rs.dish";
JRDesignQuery jq = new JRDesignQuery();
jq.setText(qu);
jd.setQuery(jq);

JasperReport jsp = JasperCompileManager.compileReport(jd);
JasperPrint prn = JasperFillManager.fillReport(jsp,null,cn);
JasperViewer.viewReport(prn);

            
//        path = getClass().getResource("/first.software/newReport.jasper").getPath();
//        path = URLDecoder.decode(path, "UTF-8");
//        Connection cn =  new Conexion().conectar();
//        Map paramotord = new HashMap();
//        JasperReport report = (JasperReport)JRLoader.loadObject(path);
//        JasperPrint print = JasperFillManager.fillReport(report, paramotord, cn);
//        JasperViewer view = new JasperViewer(print, false);
//        view.setTitle("Owaise Pakwan Center");
//        view.setVisible(true);
        
        }
        
        catch(Exception ex)
        {
                       JOptionPane.showMessageDialog(this, ex);
        }
        
        //Updated Bill
        }
        
       
        
        
        
        
        
        
        
    }//GEN-LAST:event_pbtn1ActionPerformed

    private void recc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recc1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
        
        
        
             //table
        try{  
       

        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
        
        Connection con = 
        DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

        PreparedStatement st = con.prepareStatement
        ("select r.dish as Dish,r.item as Item,r.item_quantity as Item_Quantity,r.item_rate as Item_Rate,(r.item_quantity * r.item_rate) as Total\n" +
        " from reserve r\n" +
        " inner join total p\n" +
        " on r.recipt=p.receipt \n" +
        "where p.cell='"+recc1.getText()+"'"
                + "order by r.dish");
                      
             ResultSet rs = st.executeQuery();
             table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
        //table
        
        
        
         //total
        try {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
        
        Connection con = 
        DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
        String a="0" ;
        PreparedStatement st = con.prepareStatement
        ("select sum(r.item_quantity * r.item_rate) as Total\n" +
        " from reserve r\n" +
        " inner join total p\n" +
        " on r.recipt=p.receipt \n" +
        "where p.cell='"+recc1.getText()+"'");
                      
             ResultSet rs = st.executeQuery();
             while(rs.next()){
             a = rs.getString("Total");
             
             }
             bill.setText(a);
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
        //total
        
        
        
        
         //recipt
        try {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
        
        Connection con = 
        DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
        String a="0" ;
        PreparedStatement st = con.prepareStatement
        ("select distinct r.recipt as rec\n" +
        " from reserve r\n" +
        " inner join total p\n" +
        " on r.recipt=p.receipt \n" +
        "where p.cell='"+recc1.getText()+"'");
                      
             ResultSet rs = st.executeQuery();
             while(rs.next()){
             a = rs.getString("rec");
             
             }
             recc.setText(a);
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
        //recipt
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adr;
    private javax.swing.JTextField bill;
    private javax.swing.JTextField bp;
    private javax.swing.JTextField cell;
    private javax.swing.JTextField cell1;
    private javax.swing.JTextField d;
    private javax.swing.JLabel daa;
    private javax.swing.JTextField dis;
    private javax.swing.JTextField e;
    private javax.swing.JTextField f;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JButton pbtn;
    private javax.swing.JButton pbtn1;
    private javax.swing.JTextField recc;
    private javax.swing.JTextField recc1;
    private javax.swing.JTable table;
    private javax.swing.JTextField target;
    private javax.swing.JLabel ti;
    private javax.swing.JTextField trans;
    // End of variables declaration//GEN-END:variables
}
