/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package first.software;

import static first.software.Login.da;
import static first.software.Reserve_Page.Final_Recipt_Number;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author And
 */
public class Biryani_qorma extends javax.swing.JFrame {

    /**
     * Creates new form biriani_Korma
     */
        public static String per;
        public static String per2;
        

    public Biryani_qorma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        people = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        biryani_combo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        catogory_combo = new javax.swing.JComboBox();
        jPanel17 = new javax.swing.JPanel();
        meat_combo2 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        meat_quantity2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        meat_price2 = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        quantity_rice = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        quantity_potato = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        person = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        biryani_combo1 = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        catogory_combo1 = new javax.swing.JComboBox();
        jPanel19 = new javax.swing.JPanel();
        meat_combo3 = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        meat_quantity3 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        meat_price3 = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        masala_price = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        sub = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Owaise Pakwan Center (Biryani & Qorma)");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Number of Persons");

        people.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peopleActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Select Biryani");

        biryani_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A BIRYANI (SELA)", "A BIRYANI (BASMATI)", "A YAKHNI PILAO", "A TIKKA BIRYANI" }));
        biryani_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biryani_comboActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Catogory");

        catogory_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NORMAL", "MEDUIM", "HARD" }));
        catogory_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catogory_comboActionPerformed(evt);
            }
        });

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("MEAT"));

        meat_combo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CHICKEN", "BEEF BACHYA (Hadi)", "BEEF BACHYA (bagair hadi)", "BEEF COW (Hadi)", "BEEF COW (bagair hadi)", "QEEMA COW", "QEEMA BACHYA", "NONE" }));
        meat_combo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meat_combo2ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Meat");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Quantity");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Rate");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(meat_combo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(meat_quantity2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(meat_price2)))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meat_combo2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(meat_quantity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(meat_price2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Other Expense"));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Quantity Of Rice");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Quantity Of Potato");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(quantity_rice))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(16, 16, 16)
                        .addComponent(quantity_potato, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(quantity_rice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantity_potato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel58.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel58.setText("Number of persons");

        person.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        person.setText("jLabel57");

        jLabel59.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel59.setText("Total Amount");

        total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total.setText("0 Rs...");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Select Category");

        biryani_combo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "QORMA", "KARAHI", "WHITE KARAHI", "TIKKA KARAHI", "ACHAR GHOSHT", "GREEN KARAHI", "BADAMI QORMA" }));
        biryani_combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biryani_combo1ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Catogory");

        catogory_combo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NORMAL", "MEDUIM", "HARD" }));
        catogory_combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catogory_combo1ActionPerformed(evt);
            }
        });

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("MEAT"));

        meat_combo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CHICKEN", "BEEF BACHYA (Hadi)", "BEEF BACHYA (bagair hadi)", "BEEF COW (Hadi)", "BEEF COW (bagair hadi)", "QEEMA COW", "QEEMA BACHYA", "NONE" }));
        meat_combo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meat_combo3ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Meat");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Quantity");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Rate");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(meat_combo3, 0, 199, Short.MAX_VALUE)
                            .addComponent(meat_quantity3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(meat_price3)))
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meat_combo3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(meat_quantity3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(meat_price3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder("MASALA"));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Rate");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(masala_price, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(masala_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sub.setText("SUBMIT");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });

        jMenu1.setText("File                   ");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Back");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Log Out");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(total))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(person))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(biryani_combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(catogory_combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 436, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(60, 60, 60)))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(biryani_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(catogory_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(people, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(people, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(biryani_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(catogory_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(biryani_combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(catogory_combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(person)
                            .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total)
                            .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        this.hide();
        new Reserve_Page().show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        this.hide();
        new Login().show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void peopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peopleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peopleActionPerformed

    private void biryani_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biryani_comboActionPerformed

        String slct = biryani_combo.getSelectedItem().toString();
        //        if (slct.equals("AALU BIRYANI")){
            //        meat_combo.setEnabled(false);
            //        meat_quantity.setEnabled(false);
            //        meat_price.setEditable(false);
            //        //quantity_chole.setEditable(false);
            //        }
        //        else if (slct.equals("CHANNA BIRYANI")){
            //        meat_combo.setEnabled(false);
            //        meat_quantity.setEnabled(false);
            //        meat_price.setEditable(false);
            //      //  quantity_chole.setEditable(true);
            //        }
        if (slct.equals("YAKHNI BIRNI")){
//            meat_combo.setEnabled(true);
//            meat_quantity.setEnabled(true);
//            meat_price.setEditable(true);
            // quantity_chole.setEditable(false);
        }
        else  if (slct.equals("SELA BIRYANI")){
//            meat_combo.setEnabled(true);
//            meat_quantity.setEnabled(true);
//            meat_price.setEditable(true);
            // quantity_chole.setEditable(false);
        }
        else  if (slct.equals("BASMATI BIRYANI")){
//            meat_combo.setEnabled(true);
//            meat_quantity.setEnabled(true);
//            meat_price.setEditable(true);
            // quantity_chole.setEditable(false);
        }
    }//GEN-LAST:event_biryani_comboActionPerformed

    private void catogory_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catogory_comboActionPerformed

       // recipt_number.setText(Final_Recipt_Number);
        person.setText(people.getText()+" Persons");
        per = people.getText();

        String slct = catogory_combo.getSelectedItem().toString();
        if (slct.equals("NORMAL")){
            quantity_rice.setText(String.valueOf(Integer.parseInt(per)/10));
            double a,b,c,d,e;
            a =Double.parseDouble(per)/9 ;
            b = a * 0.3;
            c = a * 1;
            // quantity_masala.setText(String.valueOf(b));
            // quantity_oil.setText(String.valueOf(c));
            quantity_potato.setText(String.valueOf(b));
            meat_quantity2.setText(String.valueOf(c));
        }
        else if (slct.equals("MEDUIM")){
            quantity_rice.setText(String.valueOf(Integer.parseInt(per)/10));
            double a,b,c,d,e;
            a =Double.parseDouble(per)/9 ;
            b = a * 0.3;
            c = a * 1;
            //quantity_masala.setText(String.valueOf(b));
            //quantity_oil.setText(String.valueOf(c));
            quantity_potato.setText(String.valueOf(b));
            meat_quantity2.setText(String.valueOf(c));
        }
        else if (slct.equals("HARD")){
            quantity_rice.setText(String.valueOf(Integer.parseInt(per)/10));
            double a1,b1,c1,d1,e1;
            a1 =Double.parseDouble(per)/9 ;
            b1 = a1 * 0.3;
            c1 = a1 * 1;

            // quantity_masala.setText(String.valueOf(b1));
            // quantity_oil.setText(String.valueOf(c1));
            quantity_potato.setText(String.valueOf(b1));
            meat_quantity2.setText(String.valueOf(c1));
        }
    }//GEN-LAST:event_catogory_comboActionPerformed

    private void meat_combo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meat_combo2ActionPerformed

         String slct = meat_combo2.getSelectedItem().toString();
 
          price prc = new price();
          prc.price();
        
         if (slct.equals("CHICKEN")){
         meat_price2.setText("");
         }

         else if (slct.equals("BEEF BACHYA (Hadi)")){
         meat_price2.setText(prc.beef_bachya_hadi_r);
         }
         
          else if (slct.equals("BEEF BACHYA (bagair hadi)")){
         meat_price2.setText(prc.beef_bachya_bagair_hadi_r);
         }
            else if (slct.equals("QEEMA BACHYA")){
         meat_price2.setText(prc.beef_bachya_bagair_hadi_r);
         }
         
          else if (slct.equals("BEEF COW (Hadi)")){
         meat_price2.setText(prc.beef_bara_hadi_r);
         }
         
         
          else if (slct.equals("BEEF COW (bagair hadi)")){
         meat_price2.setText(prc.beef_bara_bagair_hadi_r);
         }
            else if (slct.equals("QEEMA COW")){
         meat_price2.setText(prc.beef_bara_bagair_hadi_r);
         }
         
          else if (slct.equals("NONE")){
         meat_price2.setText("00");
         }
        
        
    }//GEN-LAST:event_meat_combo2ActionPerformed

    private void biryani_combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biryani_combo1ActionPerformed

        
        price prc = new price();
            prc.price();
        
         String mas_rate = biryani_combo1.getSelectedItem().toString();
        
        if(mas_rate.equals("QORMA")){
        masala_price.setText(prc.qorma_r);
        }
        

        else if(mas_rate.equals("KARAHI")){
        masala_price.setText(prc.karahi_r);
        }
        
        else if(mas_rate.equals("WHITE KARAHI")){
        masala_price.setText(prc.white_karahi_r);
        }
        else if(mas_rate.equals("TIKKA KARAHI")){
        masala_price.setText(prc.tikka_karahi_r);
        }
        else if(mas_rate.equals("ACHAR GHOSHT")){
        masala_price.setText(prc.achar_gohsht_r);
        }
        else if(mas_rate.equals("GREEN KARAHI")){
        masala_price.setText(prc.green_karahi_r);
        }
        else if(mas_rate.equals("BADAMI QORMA")){
        masala_price.setText(prc.badami_qorma_r);
        }
        
        
        
        
        String slct = biryani_combo1.getSelectedItem().toString();
        //        if (slct.equals("AALU BIRYANI")){
            //        meat_combo.setEnabled(false);
            //        meat_quantity.setEnabled(false);
            //        meat_price.setEditable(false);
            //        //quantity_chole.setEditable(false);
            //        }
        //        else if (slct.equals("CHANNA BIRYANI")){
            //        meat_combo.setEnabled(false);
            //        meat_quantity.setEnabled(false);
            //        meat_price.setEditable(false);
            //      //  quantity_chole.setEditable(true);
            //        }
        if (slct.equals("QORMA")){
//            meat_combo.setEnabled(true);
//            meat_quantity.setEnabled(true);
//            meat_price.setEditable(true);
            // quantity_chole.setEditable(false);
        }
        else  if (slct.equals("KARAHI")){
//            meat_combo.setEnabled(true);
//            meat_quantity.setEnabled(true);
//            meat_price.setEditable(true);
            // quantity_chole.setEditable(false);
        }
        else  if (slct.equals("WHITE QORMA")){
//            meat_combo.setEnabled(true);
//            meat_quantity.setEnabled(true);
//            meat_price.setEditable(true);
            // quantity_chole.setEditable(false);
        }
    }//GEN-LAST:event_biryani_combo1ActionPerformed

    private void catogory_combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catogory_combo1ActionPerformed

//        recipt_number.setText(Final_Recipt_Number);
      //  person.setText(people.getText()+" Persons");
        per2 = people.getText();

        String slct = catogory_combo1.getSelectedItem().toString();
        if (slct.equals("NORMAL")){

            double a,b,c,d,e;
            a =Double.parseDouble(per2)/10 ;
            b = a * 2;
            c = a * 1;
            // quantity_masala.setText(String.valueOf(b));
            // quantity_oil.setText(String.valueOf(c));
            meat_quantity3.setText(String.valueOf(c));
        }
        else if (slct.equals("MEDUIM")){
            double a,b,c,d,e;
            a =Double.parseDouble(per2)/10 ;
            b = a * 2;
            c = a * 1;
            //quantity_masala.setText(String.valueOf(b));
            //quantity_oil.setText(String.valueOf(c));
            meat_quantity3.setText(String.valueOf(c));
        }
        else if (slct.equals("HARD")){
            double a1,b1,c1,d1,e1;
            a1 =Double.parseDouble(per2)/10 ;
            b1 = a1 * 2;
            c1 = a1 * 1;

            // quantity_masala.setText(String.valueOf(b1));
            // quantity_oil.setText(String.valueOf(c1));
            meat_quantity3.setText(String.valueOf(c1));
        }
        
        
        
        
        
      
        
        
    }//GEN-LAST:event_catogory_combo1ActionPerformed

    private void meat_combo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meat_combo3ActionPerformed

        double mas = Double.parseDouble(meat_quantity3.getText());
       

        
         String slct = meat_combo3.getSelectedItem().toString();
 
            price prc = new price();
            prc.price();

         if (slct.equals("CHICKEN")){
         meat_price3.setText("");
         }

         else if (slct.equals("BEEF BACHYA (Hadi)")){
         meat_price3.setText(prc.beef_bachya_hadi_r);
         }
         
          else if (slct.equals("BEEF BACHYA (bagair hadi)")){
         meat_price3.setText(prc.beef_bachya_bagair_hadi_r);
         }
          
            else if (slct.equals("QEEMA BACHYA")){
         meat_price3.setText(prc.beef_bachya_bagair_hadi_r);
         }
         
          else if (slct.equals("BEEF COW (Hadi)")){
         meat_price3.setText(prc.beef_bara_hadi_r);
         }
         
         
          else if (slct.equals("BEEF COW (bagair hadi)")){
         meat_price3.setText(prc.beef_bara_bagair_hadi_r);
         }
            else if (slct.equals("QEEMA COW")){
         meat_price3.setText(prc.beef_bara_bagair_hadi_r);
         }
         
          else if (slct.equals("NONE")){
         meat_price3.setText("00");
         }
        
        

    }//GEN-LAST:event_meat_combo3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

           person.setText(Final_Recipt_Number);
        
        //     A BIRYANI (SELA)
//A BIRYANI (BASMATI)
//A YAKHNI PILAO
//A TIKKA BIRYANI
           
        //total
        try{

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
            String a="0" ;
            PreparedStatement st = con.prepareStatement
            ("select sum(item_quantity* item_rate)as total from reserve where recipt = '"+Final_Recipt_Number+"' and (dish =\n" +
            "'QORMA' or dish = 'KARAHI' or dish = 'WHITE KARAHI' or dish = 'TIKKA KARAHI' or dish = 'ACHAR GHOSHT'\n" +
            " or dish = 'GREEN KARAHI' or dish = 'BADAMI QORMA' or  dish =\n" +
            "'A BIRYANI (SELA)' or dish = 'A BIRYANI (BASMATI)' or dish = 'A YAKHNI PILAO' or dish = 'A TIKKA BIRYANI' )");

            ResultSet rs = st.executeQuery();
            while(rs.next()){
                a = rs.getString("Total");
            }
            total.setText(a);
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
        //total
    }//GEN-LAST:event_jButton1ActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed

        
        

        
        
        
        
        
        price prc = new price();
            prc.price();
        
                String bir = biryani_combo.getSelectedItem().toString();

        // Bryani Rice
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
            int ric_q = Integer.parseInt(quantity_rice.getText());

            String slct = biryani_combo.getSelectedItem().toString();
            int rate=0;
            if (slct.equals("A BIRYANI (SELA)")){
                rate = Integer.parseInt(prc.sela_biryani_r) ;
            }
            else if (slct.equals("A BIRYANI (BASMATI)")){
                rate = Integer.parseInt(prc.basmait_biryani_r) ;
            }

            else if (slct.equals("A YAKHNI PILAO")){
                rate =  Integer.parseInt(prc.yakhni_biryani_r);
            }
            else if (slct.equals("A TIKKA BIRYANI")){
                rate =  Integer.parseInt(prc.tikka_biryani_r);
            }

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','Rice',"+quantity_rice.getText()+","+rate+",'"+biryani_combo.getSelectedItem().toString()+"','"+da+"')" ;

            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }

        //Bryani Rice

        // Biryani Meat
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
          

            int meat_q = Integer.parseInt(meat_quantity2.getText());
            int meat_p = Integer.parseInt(meat_price2.getText());

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','"+meat_combo2.getSelectedItem().toString()+"',"+meat_q+","+meat_p+",'"+biryani_combo.getSelectedItem().toString()+"','"+da+"')" ;
            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }

        //Biryani Meat

        // Biryani Potato
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

            int potato_p = Integer.parseInt(quantity_potato.getText());

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','Potato',"+potato_p+","+prc.potato_r+",'"+biryani_combo.getSelectedItem().toString()+"','"+da+"')" ;
            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){

            JOptionPane.showMessageDialog(this, ex);

        }

        //Biryani Potato
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        // Qorma Meat
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

            int meat_q = Integer.parseInt(meat_quantity3.getText());
            int meat_p = Integer.parseInt(meat_price3.getText());

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','"+meat_combo3.getSelectedItem().toString()+"',"+meat_q+","+meat_p+",'"+biryani_combo1.getSelectedItem().toString()+"','"+da+"')" ;
            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }

        // Qorma Meat

        // Qorma Masala
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

          
            int mas_p = Integer.parseInt(masala_price.getText());

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','Masala',"+meat_quantity3.getText()+","+mas_p+",'"+biryani_combo1.getSelectedItem().toString()+"','"+da+"')" ;
            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }

        // Qorma Masala
        
        
        
        
                sub.setEnabled(false);

        
        
        

    }//GEN-LAST:event_subActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biryani_qorma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biryani_qorma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biryani_qorma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biryani_qorma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biryani_qorma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox biryani_combo;
    private javax.swing.JComboBox biryani_combo1;
    private javax.swing.JComboBox catogory_combo;
    private javax.swing.JComboBox catogory_combo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JTextField masala_price;
    private javax.swing.JComboBox meat_combo2;
    private javax.swing.JComboBox meat_combo3;
    private javax.swing.JTextField meat_price2;
    private javax.swing.JTextField meat_price3;
    private javax.swing.JTextField meat_quantity2;
    private javax.swing.JTextField meat_quantity3;
    private javax.swing.JTextField people;
    private javax.swing.JLabel person;
    private javax.swing.JTextField quantity_potato;
    private javax.swing.JTextField quantity_rice;
    private javax.swing.JButton sub;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
