/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package first.software;

import static first.software.Bill.Date;
import static first.software.Reserve_Page.Final_Recipt_Number;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Computer World
 */
public class Login extends javax.swing.JFrame {

    public static String da;
    public static String uss;
    public static String pss;
    public static String booker;
    public static String d1, d2, d3, d4, d5, d6, d7;

    public Login() {
        initComponents();
        SetIcon();
        System.out.println(Final_Recipt_Number);

        Calendar cal = new GregorianCalendar();
        int mon = cal.get(Calendar.MONTH) + 1;
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        da = String.valueOf(mon) + "/" + String.valueOf(day) + "/" + String.valueOf(year);
        System.out.println(da);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Passward = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Owais Returant Center");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Owais Pakwan Center");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 39, 240, 49));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/first/software/login.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(204, 204));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 190, 190));
        jPanel1.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 190, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Passward");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 80, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("User Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 80, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/first/software/submit.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setPreferredSize(new java.awt.Dimension(250, 100));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 230, 70));

        Passward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswardActionPerformed(evt);
            }
        });
        jPanel1.add(Passward, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 190, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 500, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //login
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con
                    = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
            String a = "0";
            PreparedStatement st = con.prepareStatement("select * from DD");

            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                d1 = rs.getString("d1");
                d2 = rs.getString("d2");
                d3 = rs.getString("d3");
                d4 = rs.getString("d4");
                d5 = rs.getString("d5");
                d6 = rs.getString("d6");
                d7 = rs.getString("d7");
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
        //login

        String n;
        String p;
        n = userName.getText().toString();
        p = Passward.getText().toString();

        System.out.println(n + " " + p);

        if (da.equals(d1)) {
            JOptionPane.showMessageDialog(this, "Activation Needed", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        } else if (da.equals(d2)) {
            JOptionPane.showMessageDialog(this, "Activation Needed", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        } else if (da.equals(d3)) {
            JOptionPane.showMessageDialog(this, "Activation Needed", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        } else if (da.equals(d4)) {
            JOptionPane.showMessageDialog(this, "Activation Needed", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        } else if (da.equals(d5)) {
            JOptionPane.showMessageDialog(this, "Activation Needed", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        } else if (da.equals(d6)) {
            JOptionPane.showMessageDialog(this, "Activation Needed", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        } else if (da.equals(d7)) {
            JOptionPane.showMessageDialog(this, "Activation Needed", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        } else {

            //login
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

                Connection con
                        = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
                String a = "0";
                PreparedStatement st = con.prepareStatement("select * from Loogin");

                ResultSet rs = st.executeQuery();
                while (rs.next()) {
                    uss = rs.getString("us");
                    pss = rs.getString("pass");
                    if (n.equals(uss) && p.equals(pss)) {
                        booker = uss;
                        this.hide();
                        new Welcome().show();
                    } else {
                        String s = "";
                        // JOptionPane.showMessageDialog(this, "Error","Error",JOptionPane.ERROR_MESSAGE);
                        userName.setText(s.toString());
                        Passward.setText(s.toString());

                    }
                }
            } catch (Exception ex) {
                System.out.println(ex);
            }
        //login

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void PasswardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswardActionPerformed

        //login
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con
                    = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
            String a = "0";
            PreparedStatement st = con.prepareStatement("select * from DD");

            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                d1 = rs.getString("d1");
                d2 = rs.getString("d2");
                d3 = rs.getString("d3");
                d4 = rs.getString("d4");
                d5 = rs.getString("d5");
                d6 = rs.getString("d6");
                d7 = rs.getString("d7");
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
        //login

        String n;
        String p;
        n = userName.getText().toString();
        p = Passward.getText().toString();

        System.out.println(n + " " + p);

        if (da.equals(d1)) {
            JOptionPane.showMessageDialog(this, "Activation Needed", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        } else if (da.equals(d2)) {
            JOptionPane.showMessageDialog(this, "Activation Needed", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        } else if (da.equals(d3)) {
            JOptionPane.showMessageDialog(this, "Activation Needed", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        } else if (da.equals(d4)) {
            JOptionPane.showMessageDialog(this, "Activation Needed", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        } else if (da.equals(d5)) {
            JOptionPane.showMessageDialog(this, "Activation Needed", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        } else if (da.equals(d6)) {
            JOptionPane.showMessageDialog(this, "Activation Needed", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        } else if (da.equals(d7)) {
            JOptionPane.showMessageDialog(this, "Activation Needed", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        } else {

            //login
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

                Connection con
                        = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
                String a = "0";
                PreparedStatement st = con.prepareStatement("select * from Loogin");

                ResultSet rs = st.executeQuery();
                while (rs.next()) {
                    uss = rs.getString("us");
                    pss = rs.getString("pass");
                    if (n.equals(uss) && p.equals(pss)) {
                        booker = uss;
                        this.hide();
                        new Welcome().show();
                    } else {
                        String s = "";
                        // JOptionPane.showMessageDialog(this, "Error","Error",JOptionPane.ERROR_MESSAGE);
                        userName.setText(s.toString());
                        Passward.setText(s.toString());

                    }
                }
            } catch (Exception ex) {
                System.out.println(ex);
            }
        //login

        }


    }//GEN-LAST:event_PasswardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {

            UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Passward;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables

    private void SetIcon() {

        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));

    }
}
