/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package first.software;

import static first.software.Login.da;
import static first.software.Reserve_Page.Final_Recipt_Number;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author And
 */
public class roti2 extends javax.swing.JFrame {

    /**
     * Creates new form roti2
     */
    public roti2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        people = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        sub = new javax.swing.JButton();
        person = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        taftan1 = new javax.swing.JCheckBox();
        total = new javax.swing.JLabel();
        milk1 = new javax.swing.JCheckBox();
        naan1 = new javax.swing.JCheckBox();
        maal1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setResizable(false);

        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        people.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peopleActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Number of Persons");

        jLabel58.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel58.setText("Number of persons");

        sub.setText("SUBMIT");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });

        person.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        person.setText("jLabel57");

        jLabel59.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel59.setText("Total Amount");

        taftan1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        taftan1.setText("Taftan");
        taftan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taftan1ActionPerformed(evt);
            }
        });

        total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total.setText("0 Rs...");

        milk1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        milk1.setText("Milk Roti");
        milk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milk1ActionPerformed(evt);
            }
        });

        naan1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        naan1.setText("Naan Roti");
        naan1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                naan1StateChanged(evt);
            }
        });
        naan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naan1ActionPerformed(evt);
            }
        });

        maal1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maal1.setText("Sheermaal");
        maal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maal1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Owaise Pakwan Center (Rotiyan)");

        jMenu1.setText("File                   ");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Back");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Log Out");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(total))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(person)))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(milk1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(naan1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(taftan1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(maal1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(people, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(154, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(people, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(naan1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(milk1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taftan1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maal1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(person)
                            .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total)
                            .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        person.setText(Final_Recipt_Number);

        //total
        try{

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
            String a="0" ;
            PreparedStatement st = con.prepareStatement
    ("  select sum(item_quantity* item_rate)as total from reserve where recipt = '"+Final_Recipt_Number+"'\n" +
    "   and dish ='Rotiyan'");

            ResultSet rs = st.executeQuery();
            while(rs.next()){
                a = rs.getString("Total");
            }
            total.setText(a);
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
        //total
    }//GEN-LAST:event_jButton1ActionPerformed

    private void peopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peopleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peopleActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed

        
         price prc = new price();
        prc.price();
        
        
        
          int peo = Integer.parseInt(people.getText());

        
          if(milk1.isSelected() && taftan1.isSelected() && naan1.isSelected()){
             double a,b,c;
             a = peo*0.16;
             b = peo*0.16;             
             c = peo*0.16;
             
             
               try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

           

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','"+milk1.getText()+"',"+a+","+prc.milk_roti_r+",'Rotiyan','"+da+"')" ;

            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        } 
             
           
              
                try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

           

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','"+taftan1.getText()+"',"+b+","+prc.taftan_r+",'Rotiyan','"+da+"')" ;

            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        } 
              
              
             
             try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

           

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','"+naan1.getText()+"',"+b+","+prc.naan_roti_r+",'Rotiyan','"+da+"')" ;

            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
             
             
          }
          
          
          
          
          
          
          
          
          
          else if(milk1.isSelected() && maal1.isSelected() && naan1.isSelected()){
             double a,b,c;
             a = peo*0.16;
             b = peo*0.16;             
             c = peo*0.16;
             
             
              try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

           

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','"+milk1.getText()+"',"+a+","+prc.milk_roti_r+",'Rotiyan','"+da+"')" ;

            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        } 
             
           
              
                try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

           

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','"+maal1.getText()+"',"+b+","+prc.sheermal_r+",'Rotiyan','"+da+"')" ;

            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        } 
              
              
             
             try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

           

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','"+naan1.getText()+"',"+b+","+prc.naan_roti_r+",'Rotiyan','"+da+"')" ;

            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        } 
             
             
          }
          
          
          
          
          
          
         else if (milk1.isSelected() && naan1.isSelected()){
             double a,b;
             
              
             a = peo*0.25;
             b = peo*0.25;
             
             
             
              try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

           

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','"+naan1.getText()+"',"+a+","+prc.naan_roti_r+",'Rotiyan','"+da+"')" ;

            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        } 
             
             
             
             try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

           

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','"+milk1.getText()+"',"+b+","+prc.milk_roti_r+",'Rotiyan','"+da+"')" ;

            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        } 
             
             
             
             
          }
         
         
         
         
         
         
         
         
         
        
          else if(naan1.isSelected() && taftan1.isSelected()){
             double a,b;
             a = peo*0.25;
             b = peo*0.25;
             
             
             try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

           

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','"+naan1.getText()+"',"+a+","+prc.naan_roti_r+",'Rotiyan','"+da+"')" ;

            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        } 
             
             
             
             try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

           

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','"+taftan1.getText()+"',"+b+","+prc.taftan_r+",'Rotiyan','"+da+"')" ;

            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }  
             
          }
          
          
          
          else if(milk1.isSelected() && taftan1.isSelected()){
          double a,b;
             a = peo*0.25;
             b = peo*0.25;
             
             
              try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

           

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','"+milk1.getText()+"',"+a+","+prc.milk_roti_r+",'Rotiyan','"+da+"')" ;

            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        } 
             
             
             
             try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

           

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','"+taftan1.getText()+"',"+b+","+prc.taftan_r+",'Rotiyan','"+da+"')" ;

            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        } 
             
          }
          
          
          
          
          
          
          
          
          
          else if(naan1.isSelected() && maal1.isSelected()){
          double a,b;
             a = peo*0.25;
             b = peo*0.25;
             
             
              try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

           

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','"+naan1.getText()+"',"+a+","+prc.naan_roti_r+",'Rotiyan','"+da+"')" ;

            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        } 
             
             
             
             try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

           

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','"+maal1.getText()+"',"+b+","+prc.sheermal_r+",'Rotiyan','"+da+"')" ;

            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        } 
             
          }
          
          
          
          
          
          
          
          
          
          
          else if(milk1.isSelected() && maal1.isSelected()){
          double a,b;
             a = peo*0.25;
             b = peo*0.25;
             
             try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

           

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','"+milk1.getText()+"',"+a+","+prc.milk_roti_r+",'Rotiyan','"+da+"')" ;

            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        } 
             
             
             
             try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

           

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','"+maal1.getText()+"',"+b+","+prc.sheermal_r+",'Rotiyan','"+da+"')" ;

            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        } 
             
             
          }
          
          
          
          
          
          
          
          
          
          
          else if(naan1.isSelected()){
          double a;
             a = peo*0.50;
             try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

           

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','"+naan1.getText()+"',"+a+","+prc.naan_roti_r+",'Rotiyan','"+da+"')" ;

            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        } 
             }
          
          
          
          
          
          
          
          
          
          
          else if(milk1.isSelected()){
          double a;
             a = peo*0.50;
             
             try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

           

            String q = "insert into reserve values"
            + " ('"+Final_Recipt_Number+"','"+milk1.getText()+"',"+a+","+prc.milk_roti_r+",'Rotiyan','"+da+"')" ;

            Statement st = con.createStatement();
            st.execute(q);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        } 
             
             
             }
          
                  
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
       
        
        
        
        
        
        
        
         
           
                 sub.setEnabled(false);
  
           
  
           
        
    }//GEN-LAST:event_subActionPerformed

    private void taftan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taftan1ActionPerformed

         
    }//GEN-LAST:event_taftan1ActionPerformed

    private void milk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milk1ActionPerformed

         
    }//GEN-LAST:event_milk1ActionPerformed

    private void naan1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_naan1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_naan1StateChanged

    private void naan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naan1ActionPerformed

       

    }//GEN-LAST:event_naan1ActionPerformed

    private void maal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maal1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        this.hide();
        new Reserve_Page().show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        this.hide();
        new Login().show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(roti2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(roti2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(roti2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(roti2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new roti2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JCheckBox maal1;
    private javax.swing.JCheckBox milk1;
    private javax.swing.JCheckBox naan1;
    private javax.swing.JTextField people;
    private javax.swing.JLabel person;
    private javax.swing.JButton sub;
    private javax.swing.JCheckBox taftan1;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
