/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package first.software;

import static first.software.Bill.Date;
import static first.software.Bill.Time;
import static first.software.Bill.b_date;
import static first.software.Reserve_Page.Final_Recipt_Number;
import static first.software.Reserve_Page.Recipt_number_from_database;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author And
 */
public class time extends javax.swing.JFrame {

   public static String a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,bb;
   public static String radio;
   public static String s_Date;
   public int count;
    
    public time() {
        initComponents();
        
        s_Date = Date ;
        count = 0; 
         select_date.setText(Date);
//       K
        
        try{  
       

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
        
        Connection con = 
        DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

            PreparedStatement st = con.prepareStatement("select * from booking where [date] = '"+select_date.getText()+"'");
                      
            ResultSet rs = st.executeQuery();
             while(rs.next()){
             a = rs.getString("B1");
             b = rs.getString("B2");
             c = rs.getString("B3");
             d = rs.getString("B4");
             e = rs.getString("B5");
             f = rs.getString("B6");
             g = rs.getString("B7");
             h = rs.getString("B8");
             i = rs.getString("B9");
             j = rs.getString("B10");
             k = rs.getString("B11");
             l = rs.getString("B12");
             m = rs.getString("B13");
             n = rs.getString("B14");
             o = rs.getString("B15");
             p = rs.getString("B16");
             q = rs.getString("B17");
             r = rs.getString("B18");
             s = rs.getString("B19");
             t = rs.getString("B20");
             u = rs.getString("B21");
             v = rs.getString("B22");
             w = rs.getString("B23");
             x = rs.getString("B24");
             y = rs.getString("B25");
             z = rs.getString("B26");
             aa = rs.getString("B27");
             bb = rs.getString("B28");
             
             }
             System.out.println(Recipt_number_from_database);
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
 
        
        a1.setText(a);
        a2.setText(b);
        a3.setText(c);
        a4.setText(d);
        a5.setText(e);
        a6.setText(f);
        a7.setText(g);
        a8.setText(h);
        a9.setText(i);
        a10.setText(j);
        a11.setText(k);
        a12.setText(l);
        a13.setText(m);
        a14.setText(n);
        a15.setText(o);
        a16.setText(p);
        a17.setText(q);
        a18.setText(r);
        a19.setText(s);
        a20.setText(t);
        a21.setText(u);
        a22.setText(v);
        a23.setText(w);
        a24.setText(x);
        a25.setText(y);
        a26.setText(z);
        a27.setText(aa);
        a28.setText(bb);
        
        
        
        
        
        // Database
        
        
        //Date
        da.setText(Date);
        ti.setText(Time);
        select_date.setText(Date);
        //Time
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        a4 = new javax.swing.JTextField();
        a5 = new javax.swing.JTextField();
        a6 = new javax.swing.JTextField();
        a7 = new javax.swing.JTextField();
        a8 = new javax.swing.JTextField();
        a9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        da = new javax.swing.JLabel();
        ti = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        r6 = new javax.swing.JRadioButton();
        r7 = new javax.swing.JRadioButton();
        r8 = new javax.swing.JRadioButton();
        r9 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        sdt = new com.toedter.calendar.JDateChooser();
        a2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        select_date = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        a10 = new javax.swing.JTextField();
        r10 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        a11 = new javax.swing.JTextField();
        r11 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        a12 = new javax.swing.JTextField();
        r12 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        a13 = new javax.swing.JTextField();
        r13 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        a14 = new javax.swing.JTextField();
        r14 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        a15 = new javax.swing.JTextField();
        r15 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        a16 = new javax.swing.JTextField();
        r16 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        a17 = new javax.swing.JTextField();
        r17 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        a19 = new javax.swing.JTextField();
        r19 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        a18 = new javax.swing.JTextField();
        r18 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        a20 = new javax.swing.JTextField();
        r20 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        a21 = new javax.swing.JTextField();
        r21 = new javax.swing.JRadioButton();
        a22 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        r22 = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        a23 = new javax.swing.JTextField();
        r23 = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        a24 = new javax.swing.JTextField();
        r24 = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        a25 = new javax.swing.JTextField();
        r25 = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        a26 = new javax.swing.JTextField();
        r26 = new javax.swing.JRadioButton();
        a27 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        r27 = new javax.swing.JRadioButton();
        r28 = new javax.swing.JRadioButton();
        a28 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setText("11 to 11:30");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setText("11:30 to 12");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 20));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setText("12 to 12:30");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, 20));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setText("12:30 to 1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 60, 20));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setText("1 to 1:30");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 30));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setText("1:30 to 2");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, 20));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel7.setText("2 to 2:30");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel8.setText("2:30 to 3");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, 20));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel9.setText("3 to 3:30");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, 20));
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 184, -1));
        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 184, -1));
        getContentPane().add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 183, 21));

        a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a5ActionPerformed(evt);
            }
        });
        getContentPane().add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 183, -1));
        getContentPane().add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 183, -1));
        getContentPane().add(a7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 183, -1));
        getContentPane().add(a8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 183, -1));
        getContentPane().add(a9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 183, 20));

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 80, 40));

        da.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        da.setText("Date");
        getContentPane().add(da, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, 126, -1));

        ti.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ti.setText("Date");
        getContentPane().add(ti, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 580, 126, -1));

        btn.add(r1);
        getContentPane().add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        btn.add(r2);
        getContentPane().add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 40, 30));

        btn.add(r3);
        getContentPane().add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 30, 20));

        btn.add(r4);
        getContentPane().add(r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 30, 20));

        btn.add(r5);
        getContentPane().add(r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 209, 30, -1));

        btn.add(r6);
        getContentPane().add(r6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 239, 20, -1));

        btn.add(r7);
        getContentPane().add(r7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, 40));

        btn.add(r8);
        getContentPane().add(r8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 20, 30));

        btn.add(r9);
        getContentPane().add(r9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 20, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 40, 260));

        jButton2.setText(">");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 40, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Select Date");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 100, 20));
        getContentPane().add(sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 260, -1));
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 184, -1));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, 450, 10));

        select_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_dateActionPerformed(evt);
            }
        });
        getContentPane().add(select_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 390, -1));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel13.setText("3:30 to 4");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 60, 20));
        getContentPane().add(a10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 183, -1));

        btn.add(r10);
        getContentPane().add(r10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 20, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel14.setText("4 to 4:30");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));
        getContentPane().add(a11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 183, -1));

        btn.add(r11);
        getContentPane().add(r11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 20, -1));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel15.setText("4:30 to 5");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));
        getContentPane().add(a12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 183, -1));

        btn.add(r12);
        getContentPane().add(r12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 20, -1));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel16.setText("5 to 5:30");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));
        getContentPane().add(a13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 183, -1));

        btn.add(r13);
        getContentPane().add(r13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 20, -1));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel17.setText("5:30 to 6");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, -1, -1));
        getContentPane().add(a14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 183, -1));

        btn.add(r14);
        getContentPane().add(r14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 20, -1));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel18.setText("6 to 6:30");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));
        getContentPane().add(a15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 183, -1));

        btn.add(r15);
        getContentPane().add(r15, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 20, -1));

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel19.setText("7 to 7:30");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));
        getContentPane().add(a16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 183, -1));

        btn.add(r16);
        getContentPane().add(r16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 20, -1));

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel20.setText("6:30 to 7");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));
        getContentPane().add(a17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 183, -1));

        btn.add(r17);
        getContentPane().add(r17, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 20, -1));

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel21.setText("8 to 8:30");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        a19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a19ActionPerformed(evt);
            }
        });
        getContentPane().add(a19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 183, -1));

        btn.add(r19);
        getContentPane().add(r19, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 20, -1));

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel22.setText("7:30 to 8");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));
        getContentPane().add(a18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 183, -1));

        btn.add(r18);
        getContentPane().add(r18, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 20, -1));

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel23.setText("8:30 to 9");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        a20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a20ActionPerformed(evt);
            }
        });
        getContentPane().add(a20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 183, -1));

        btn.add(r20);
        getContentPane().add(r20, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 20, -1));

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel24.setText("9 to 9:30");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, -1));

        a21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a21ActionPerformed(evt);
            }
        });
        getContentPane().add(a21, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 183, -1));

        btn.add(r21);
        getContentPane().add(r21, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 20, -1));

        a22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a22ActionPerformed(evt);
            }
        });
        getContentPane().add(a22, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 183, -1));

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel25.setText("9:30 to 10");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        btn.add(r22);
        getContentPane().add(r22, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 20, -1));

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel26.setText("10 to 10:30");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, -1));

        a23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a23ActionPerformed(evt);
            }
        });
        getContentPane().add(a23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 183, -1));

        btn.add(r23);
        getContentPane().add(r23, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 20, -1));

        jLabel27.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel27.setText("10:30 to 11");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        a24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a24ActionPerformed(evt);
            }
        });
        getContentPane().add(a24, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 183, -1));

        btn.add(r24);
        getContentPane().add(r24, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 20, -1));

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel28.setText("11 to 11:30");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, -1, -1));

        a25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a25ActionPerformed(evt);
            }
        });
        getContentPane().add(a25, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 183, -1));

        btn.add(r25);
        getContentPane().add(r25, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 20, -1));

        jLabel29.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel29.setText("11:30 to 12");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        a26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a26ActionPerformed(evt);
            }
        });
        getContentPane().add(a26, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, 183, -1));

        btn.add(r26);
        getContentPane().add(r26, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, 20, -1));

        a27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a27ActionPerformed(evt);
            }
        });
        getContentPane().add(a27, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, 183, -1));

        jLabel30.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel30.setText("12 to 12:30");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, -1, -1));

        btn.add(r27);
        getContentPane().add(r27, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, 20, -1));

        btn.add(r28);
        getContentPane().add(r28, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 20, -1));

        a28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a28ActionPerformed(evt);
            }
        });
        getContentPane().add(a28, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 183, -1));

        jLabel31.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel31.setText("12:30 to 1");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, -1, -1));

        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 90, 50));

        jMenu2.setText("Eixt         ");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Log Out              ");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Back");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Exit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void data(){
    
        Calendar cal = new GregorianCalendar();
        int mon = cal.get(Calendar.MONTH)+1;
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        s_Date = String.valueOf(day)+"/"+String.valueOf(mon)+"/"+String.valueOf(year);
        
   
         
    }
    
     public void data(int a){
    
        Calendar cal = new GregorianCalendar();
        int mon = cal.get(Calendar.MONTH)+1;
        int year = cal.get(Calendar.YEAR);
        if((Calendar.MONTH)+1 == 12){
        count = 1;
        }
        int day = cal.get(Calendar.DAY_OF_MONTH)+count;
        s_Date = String.valueOf(day)+"/"+String.valueOf(mon)+"/"+String.valueOf(year);
        
   
         
    }
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        this.hide();
        new Login().show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

        this.hide();
        new Bill().show();
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void a5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

           b_date = select_date.getText();
        
        //radio
          if (r1.isSelected()){
          radio = "11 : 30 Am ";
          }
          else if (r2.isSelected()){
          radio = "03 : 30 Pm";
          }
          else if (r3.isSelected()){
          radio = "12 : 00 Pm";
          }
          
          else if (r4.isSelected()){
          radio = "12 : 30 Pm";
          }
          
          else if (r5.isSelected()){
          radio = "01 : 00 Pm";
          }
          
          else if (r6.isSelected()){
          radio = "01 : 30 Pm";
          }
          
          else if (r7.isSelected()){
          radio = "02 : 00 Pm";
          }
          
          else if (r8.isSelected()){
          radio = "02 : 30 Pm";
          }
          
          else if (r9.isSelected()){
          radio = "03 : 00 Pm";
          }
          else if (r10.isSelected()){
          radio = "04 : 00 Pm";
          }
          else if (r11.isSelected()){
          radio = "04 : 30 Pm";
          }
          else if (r12.isSelected()){
          radio = "05 : 00 Pm";
          }
          else if (r13.isSelected()){
          radio = "05 : 30 Pm";
          }
          else if (r14.isSelected()){
          radio = "06 : 00 Pm";
          }
          else if (r15.isSelected()){
          radio = "06 : 30 Pm";
          }
          else if (r16.isSelected()){
          radio = "07 : 00 Pm";
          }
          else if (r17.isSelected()){
          radio = "07 : 30 Pm";
          }
          else if (r18.isSelected()){
          radio = "08 : 00 Pm";
          }
          else if (r19.isSelected()){
          radio = "08 : 30 Pm";
          }
          else if (r20.isSelected()){
          radio = "09 : 00 Pm";
          }
          else if (r21.isSelected()){
          radio = "09 : 30 Pm";
          }
          else if (r22.isSelected()){
          radio = "10 : 00 Pm";
          }
          else if (r23.isSelected()){
          radio = "10 : 30 Pm";
          }
          else if (r24.isSelected()){
          radio = "11 : 00 Pm";
          }
          else if (r25.isSelected()){
          radio = "11 : 30 Pm";
          }
          else if (r26.isSelected()){
          radio = "12 : 00 Am";
          }
          else if (r27.isSelected()){
          radio = "12 : 30 Am";
          }
          else if (r28.isSelected()){
          radio = "01 : 00 Am";
          }
          
          
          
          
          
          
          
          
        //rDIO
        
        
        
        
        //Update
 try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con =
            DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");       

            String q = "update booking set B1='"+a1.getText()+"',B2='"+a2.getText()+"',B3='"+a3.getText()+"',"
                    + "B4='"+a4.getText()+"',B5='"+a5.getText()+"',\n" +
"B6='"+a6.getText()+"',B7='"+a7.getText()+"',B8='"+a8.getText()+"',B9='"+a9.getText()+"',B10='"+a10.getText()+"',\n" +
"B11='"+a11.getText()+"',B12='"+a12.getText()+"',B13='"+a13.getText()+"',B14='"+a14.getText()+"',B15='"+a15.getText()+"',\n" +
"B16='"+a16.getText()+"',B17='"+a17.getText()+"',B18='"+a18.getText()+"',B19='"+a19.getText()+"',B20='"+a20.getText()+"',\n" +
"B21='"+a21.getText()+"',B22='"+a22.getText()+"',B23='"+a23.getText()+"',B24='"+a24.getText()+"',B25='"+a25.getText()+"',\n" +
"B26='"+a26.getText()+"',B27='"+a27.getText()+"',B28='"+a28.getText()+"'\n" +
"where [date] = '"+select_date.getText()+"'" ;

            
           // "WHERE [date] = '"+select_date.getText()+"'" ;
            Statement st = con.createStatement();
            st.execute(q);

        }
            catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }        
        //Update
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
      
        
        SimpleDateFormat sdf = new SimpleDateFormat("d/M/yyyy");
        String ssd = sdf.format(sdt.getDate());
        select_date.setText(ssd);
        System.out.println(select_date.getText());
        
        
             try{  
       

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
        
        Connection con = 
        DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");

            PreparedStatement st = con.prepareStatement("select * from booking where [date] = '"+select_date.getText()+"'");
                      
            ResultSet rs = st.executeQuery();
             while(rs.next()){
             a = rs.getString("B1");
             b = rs.getString("B2");
             c = rs.getString("B3");
             d = rs.getString("B4");
             e = rs.getString("B5");
             f = rs.getString("B6");
             g = rs.getString("B7");
             h = rs.getString("B8");
             i = rs.getString("B9");
             j = rs.getString("B10");
             k = rs.getString("B11");
             l = rs.getString("B12");
             m = rs.getString("B13");
             n = rs.getString("B14");
             o = rs.getString("B15");
             p = rs.getString("B16");
             q = rs.getString("B17");
             r = rs.getString("B18");
             s = rs.getString("B19");
             t = rs.getString("B20");
             u = rs.getString("B21");
             v = rs.getString("B22");
             w = rs.getString("B23");
             x = rs.getString("B24");
             y = rs.getString("B25");
             z = rs.getString("B26");
             aa = rs.getString("B27");
             bb = rs.getString("B28");
             
             }
             System.out.println(Recipt_number_from_database);
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
 
        
        a1.setText(a);
        a2.setText(b);
        a3.setText(c);
        a4.setText(d);
        a5.setText(e);
        a6.setText(f);
        a7.setText(g);
        a8.setText(h);
        a9.setText(i);
        a10.setText(j);
        a11.setText(k);
        a12.setText(l);
        a13.setText(m);
        a14.setText(n);
        a15.setText(o);
        a16.setText(p);
        a17.setText(q);
        a18.setText(r);
        a19.setText(s);
        a20.setText(t);
        a21.setText(u);
        a22.setText(v);
        a23.setText(w);
        a24.setText(x);
        a25.setText(y);
        a26.setText(z);
        a27.setText(aa);
        a28.setText(bb);
        
        
        
        
        
        // Database
        
        da.setText(select_date.getText());
        ti.setText(Time);
        
        // Database
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void select_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_dateActionPerformed

    private void a19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a19ActionPerformed

    private void a20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a20ActionPerformed

    private void a21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a21ActionPerformed

    private void a22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a22ActionPerformed

    private void a23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a23ActionPerformed

    private void a24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a24ActionPerformed

    private void a25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a25ActionPerformed

    private void a26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a26ActionPerformed

    private void a27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a27ActionPerformed

    private void a28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a28ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        
        try{
            
  
            
Connection cn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=owaise;username=admin;password=admin");
//String report="E:\\ibti\\Data\\Java Data\\Owaise Pakwan Center\\Resturant\\src\\first\\software\\newReport.jrxml";

JasperDesign jd = 
JRXmlLoader.load("C:\\Users\\sony\\Documents\\NetBeansProjects\\Catering Software\\Owaise Pakwan Center (aptech)\\Resturant\\src\\first\\software\\pakwan.jrxml");


String qu = "select * from booking where "
        + "[date]='"+select_date.getText()+"'";
JRDesignQuery jq = new JRDesignQuery();
jq.setText(qu);
jd.setQuery(jq);

JasperReport jsp = JasperCompileManager.compileReport(jd);
JasperPrint prn = JasperFillManager.fillReport(jsp,null,cn);
JasperViewer.viewReport(prn);
         
            
//        path = getClass().getResource("/first.software/newReport.jasper").getPath();
//        path = URLDecoder.decode(path, "UTF-8");
//        Connection cn =  new Conexion().conectar();
//        Map paramotord = new HashMap();
//        JasperReport report = (JasperReport)JRLoader.loadObject(path);
//        JasperPrint print = JasperFillManager.fillReport(report, paramotord, cn);
//        JasperViewer view = new JasperViewer(print, false);
//        view.setTitle("Owaise Pakwan Center");
//        view.setVisible(true);
        
        }
        
        catch(Exception ex)
        {
                       JOptionPane.showMessageDialog(this, ex);
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new time().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a10;
    private javax.swing.JTextField a11;
    private javax.swing.JTextField a12;
    private javax.swing.JTextField a13;
    private javax.swing.JTextField a14;
    private javax.swing.JTextField a15;
    private javax.swing.JTextField a16;
    private javax.swing.JTextField a17;
    private javax.swing.JTextField a18;
    private javax.swing.JTextField a19;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a20;
    private javax.swing.JTextField a21;
    private javax.swing.JTextField a22;
    private javax.swing.JTextField a23;
    private javax.swing.JTextField a24;
    private javax.swing.JTextField a25;
    private javax.swing.JTextField a26;
    private javax.swing.JTextField a27;
    private javax.swing.JTextField a28;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JTextField a5;
    private javax.swing.JTextField a6;
    private javax.swing.JTextField a7;
    private javax.swing.JTextField a8;
    private javax.swing.JTextField a9;
    private javax.swing.ButtonGroup btn;
    private javax.swing.JLabel da;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r10;
    private javax.swing.JRadioButton r11;
    private javax.swing.JRadioButton r12;
    private javax.swing.JRadioButton r13;
    private javax.swing.JRadioButton r14;
    private javax.swing.JRadioButton r15;
    private javax.swing.JRadioButton r16;
    private javax.swing.JRadioButton r17;
    private javax.swing.JRadioButton r18;
    private javax.swing.JRadioButton r19;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r20;
    private javax.swing.JRadioButton r21;
    private javax.swing.JRadioButton r22;
    private javax.swing.JRadioButton r23;
    private javax.swing.JRadioButton r24;
    private javax.swing.JRadioButton r25;
    private javax.swing.JRadioButton r26;
    private javax.swing.JRadioButton r27;
    private javax.swing.JRadioButton r28;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JRadioButton r6;
    private javax.swing.JRadioButton r7;
    private javax.swing.JRadioButton r8;
    private javax.swing.JRadioButton r9;
    private com.toedter.calendar.JDateChooser sdt;
    private javax.swing.JTextField select_date;
    private javax.swing.JLabel ti;
    // End of variables declaration//GEN-END:variables
}
